FROM jupyter/scipy-notebook
ARG CODE_RELEASE
ARG DEBIAN_FRONTEND="noninteractive"

USER root
ENV HOME="/config"

# 安装必要的依赖
RUN apt-get update && apt-get install -y \
    curl \
    git \
    zip \
    unzip \
    && apt-get clean \
    echo "**** install code-server ****" && \
    mkdir -p /app/code-server

# 安装Code-Server
RUN curl -o /tmp/code-server.tar.gz -L "https://github.com/coder/code-server/releases/download/v4.90.3/code-server-4.90.3-linux-arm64.tar.gz"
RUN tar xf /tmp/code-server.tar.gz -C /app/code-server --strip-components=1

RUN rm -rf /config/* /tmp/* /var/lib/apt/lists/* /var/tmp/*

#RUN curl -fsSL https://code-server.dev/install.sh | sh

ENV PATH=/app/code-server/bin:$PATH

USER $NB_UID

# 启动脚本
COPY ./images/jupyter-codeserver/startcode-server.sh /usr/local/bin/

USER root

RUN chmod +x /usr/local/bin/startcode-server.sh
USER $NB_UID

# add local files
COPY ./images/jupyter-codeserver/root /

CMD ["/usr/local/bin/startcode-server.sh"]
CMD ["start-notebook.py"]

# 暴露端口
EXPOSE 8888 8080
