FROM jupyter/pytorch-notebook

USER root

# 安装必要的依赖
RUN apt-get update && apt-get install -y \
    curl \
    && apt-get clean

# 安装Code-Server
RUN curl -fsSL https://code-server.dev/install.sh | sh

# 暴露端口
EXPOSE 8888 8080

USER $NB_UID

# 启动脚本
COPY ./images/jupyter-codeserver/startcode-server.sh /usr/local/bin/

USER root

RUN chmod +x /usr/local/bin/startcode-server.sh
USER $NB_UID

CMD ["/usr/local/bin/startcode-server.sh"]
