FROM jupyter/scipy-notebook
ARG CODE_RELEASE

USER root
ENV HOME="/config"

# 安装必要的依赖
RUN apt-get update && apt-get install -y \
    curl \
    git \
    zip \
    unzip \
    && apt-get clean \
    echo "**** install code-server ****" && \
    mkdir -p /app/code-server && \
    if [ -z ${CODE_RELEASE+x} ]; then \
        CODE_RELEASE=111.11.1
    fi


# 安装Code-Server
#RUN curl -fsSL https://code-server.dev/install.sh | sh

# 暴露端口
EXPOSE 8888 8080

USER $NB_UID

# 启动脚本
COPY ./images/jupyter-codeserver/startcode-server.sh /usr/local/bin/

USER root

RUN chmod +x /usr/local/bin/startcode-server.sh
USER $NB_UID

CMD ["/usr/local/bin/startcode-server.sh"]
